# THANKS!
# https://travis-ci.org/peterbe/premailer

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.

sudo: false
dist: trusty

env:
 - global:
    - secure: mcUCykGm4bUZ3CaW6AxrIMFzuAYjA98VIz6YmYTmM0/8sp/B/54JtQS/j0ehCD6B5BwyW6diVcaQA2c7bovI23GyeTT+TgfkuKRkzDcoY51ZsMDdsflJ94zV7TEIS31eCeq42IBYdHZeVZp/L7EXOzFjVmvYhboJiwnsPybpCfpIH369fjYKuVmutccD890nP8Bzg8iegssVldgsqDagkuLy0wObAVH0FKnqiIPtFoMf3mDeVmK2AkF1Xri1edsPl4wDIu1Ko3RCRgfr6NxzuNSh6f4Z6zmJLB4ONkpb3fAa9Lt+VjJjdSjCBT1OGhJdP7NlO5vSnS5TCYvgFqNSXqqJx9BNzZ9/esszP7DJBe1yq1aNwAvJ7DlSzh5rvLyXR4VWHXRIR3hOWDTRwCsJQJctCLpbDAFJupuZDcvqvPNj8dY5MSCu6NroXMMFmxJHIt3Hdzr+hV9RNJkQRR4K5bR+ewbJ/6h9rjX6Ot6kIsjJkmEwx1jllxi4+gSRtNQ/O4NCi3fvHmpG2pCr7Jz0+eNL2d9wm4ZxX1s18ZSAZ5XcVJdx8zL4vjSnwAQoFXzmx0LcpK6knEgw/hsTFovSpe5p3oLcERfSd7GmPm84Qr8U4YFKXpeQlb9k5BK9MaQVqI4LyaM2h4Xx+wc0QlEQlUOfwD4B2XrAYXFIq1PAEic=
 - PIP_DOWNLOAD_CACHE="pip_cache"

language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
      - libjpeg8
      - libjpeg8-dev

# See tox.ini for env list
env:
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py27-django110
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py34-django110
- TOXENV=py35-django18
- TOXENV=py35-django19
- TOXENV=py35-django110

install:
  - pip install tox>=2.1 coveralls

script:
  - tox -e $TOXENV

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy: "echo 'Deploying source language to transifex...'"
deploy:
  - provider: transifex
    username: someuser
    password:
      secure: ABCD1234...5678WXYZ
    on:
      branch: transifex-test
